### PR TITLE
Updates example descriptions. Remove the overlay of 6 DOF plots

### PR DESCRIPTION
**Pull request by ssolson**
Kelly I have updated the import of wave as discussed in our call yesterday.

I found the retention of plotting 6 DOF overlays to not add value after the first few and I removed them.

Can you let me know if the error discussed on the PR appears for you when calling the elevation spectrum function?

In the end I think that creating an elevation spectrum from time series wave data does not display the power of the data available from the WEC-SIM run. E.g. can we analyze something that uses PTO,  body, or mooring data from WEC-SIM?

### CODE REVIEW

**Comment by kmruehl** [comment]
@ssolson I think that plotting the mooring and constraint loads in all DOFs has value because it visually displays the data, and shows the user which DOFs are of concern for mooring and constraint loads. This is relevant since the DOFs with primary loads are not necessarily the same DOF as the primary displacement. But it is not necessary for the purpose of this example.

image
image
image

Regarding application of MHKiT to WEC-Sim data, I agree that generating a wave elevation spectrum is not exciting, but the intent of this PR is to develop a WEC-Sim io function for MHKiT so that simulated data can be used for other modules, e.g. `mhkit.loads` and `mhkit.wave.performance`. In other words, there will be more interesting applications of WEC-Sim that we can include at a later date, for example using a batch run of WEC-Sim to generate power matrices and performs loads analysis.

**Comment by ssolson** [comment]
Okay that sounds good. On the plotting would you add some discussion in the example explaining why each of the plots is useful to see? E.g. in the plots above you could talk about dof 1 and 3.

On the processing of the data that makes sense that we need to import the data to start to build out functionality which uses it but I just want to be sure that there is not some part of Wave, loads, or power module that we can currently use to show the power of importing WEC SIM data? I will ask for input from Rebecca and Chris on the primary PR as they authored the last 2 modules.

**Comment by ssolson** [comment]
oh also what was the issue?

**Comment by kmruehl** [comment]
@ssolson the issue was that you never defined `ws_spectrum` 
 
``` python
# Use the MHKiT Wave Module to calculate wave spectrum from the WEC-Sim Wave Class Data
sample_rate=60
nnft=1000        # Number of bins in the Fast Fourier Transform
wave.resource.elevation_spectrum(wave_data, sample_rate, nnft)

# Plot calcualed wave Spectrum
spect_plot = wave.graphics.plot_spectrum(ws_spectrum)
spect_plot = spect_plot.set_xlim([0, 4])
```
All I did was add `ws_spectrum` 

``` python
# Use the MHKiT Wave Module to calculate wave spectrum from the WEC-Sim Wave Class Data
sample_rate=60
nnft=1000        # Number of bins in the Fast Fourier Transform
ws_spectrum = wave.resource.elevation_spectrum(wave_data, sample_rate, nnft)

# Plot calcualed wave Spectrum
spect_plot = wave.graphics.plot_spectrum(ws_spectrum)
spect_plot = spect_plot.set_xlim([0, 4])
```

**Comment by kmruehl** [comment]
> 
> 
> Okay that sounds good. On the plotting would you add some discussion in the example explaining why each of the plots is useful to see? E.g. in the plots above you could talk about dof 1 and 3.
> 
> On the processing of the data that makes sense that we need to import the data to start to build out functionality which uses it but I just want to be sure that there is not some part of Wave, loads, or power module that we can currently use to show the power of importing WEC SIM data? I will ask for input from Rebecca and Chris on the primary PR as they authored the last 2 modules.

@ssolson which plots are you referring to? I did not re-add the mooring or constraint plots, I kept them as is based on this PR. I was only explaining why I thought they were useful in the first place.

**Comment by ssolson** [comment]
Not defining the spectrum was not the issue. Check the stack.
image

As you can see everything is set up here correctly. I apologize for sending the PR version to you incorrectly. Let me see if I still get this error.

Okay if you left the plots out then no need to add a description. I thought you had added them back I was suggesting that was okay with me but thought the plots should be supported by some discussion.

**Comment by ssolson** [comment]
Yes I still get the same error
image

**Comment by kmruehl** [comment]
@ssolson I'm not sure what the issue is then. I saw in the stack that you had in fact defined `ws_spectrum` in the example screenshot, but it was missing from the example. I had an error when I ran the example (I thought it was the same error, but maybe not), added the `ws_spectrum` definition back in, and the example ran fine for me. I also noticed in your example screenshot that the notebook had not been executed all at once (execution of the line as `In[41]` versus `In[16]`), and thought that may have been the issue, but based on your latest screenshot, that does not appear to be the case.

**Pull request merged**
